"""initialize currencies

Revision ID: 2b25d44f27ee
Revises: 64d6f4ee3a55
Create Date: 2026-02-06 10:46:06.680351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import requests

# revision identifiers, used by Alembic.
revision: str = '2b25d44f27ee'
down_revision: Union[str, Sequence[str], None] = '64d6f4ee3a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    metadata = sa.MetaData()
    metadata.reflect(bind=op.get_bind(), only=["currency"])
    currency_table = metadata.tables["currency"]
    currencies_json = requests.get(
        "https://raw.githubusercontent.com/ourworldincode/currency/refs/heads/main/currencies.json"
    ).json()
    op.bulk_insert(currency_table, [{"iso": iso} for iso in currencies_json.keys() if len(iso) == 3])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
