"""add unique constraint to currency isos

Revision ID: 64d6f4ee3a55
Revises: 82993b44f363
Create Date: 2026-02-06 10:44:24.619179

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '64d6f4ee3a55'
down_revision: Union[str, Sequence[str], None] = '82993b44f363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


currency_iso_unique_constraint_name = "currency_iso_unique"

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.create_unique_constraint(currency_iso_unique_constraint_name, ['iso'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.drop_constraint(currency_iso_unique_constraint_name, type_='unique')

    # ### end Alembic commands ###
