"""Initial DB structure

Revision ID: 82993b44f363
Revises:
Create Date: 2026-02-05 16:42:40.896827

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82993b44f363"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("iso", sa.String(length=3), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rate_date", sa.Date(), nullable=False),
        sa.Column("base_currency_id", sa.Integer(), nullable=False),
        sa.Column("quote_currency_id", sa.Integer(), nullable=False),
        sa.Column("side", sa.Enum("BUY", "SELL", name="sideenum"), nullable=False),
        sa.Column("rate", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["base_currency_id"],
            ["currency.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quote_currency_id"],
            ["currency.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transaction",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("rate_used_id", sa.Integer(), nullable=False),
        sa.Column("base_amount", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("foreign_amount", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column(
            "rounding_adjustment", sa.Numeric(precision=20, scale=4), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["rate_used_id"],
            ["rate.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction")
    op.drop_table("rate")
    op.drop_table("currency")
    # ### end Alembic commands ###
