"""rate for a given date, side, base and quote currency should be unique

Revision ID: 999f1bd12599
Revises: 2b25d44f27ee
Create Date: 2026-02-06 14:22:49.006208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999f1bd12599'
down_revision: Union[str, Sequence[str], None] = '2b25d44f27ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


constraint_name = "rate_unique_constraint"

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rate', schema=None) as batch_op:
        batch_op.create_unique_constraint(constraint_name, ['rate_date', 'base_currency_id', 'quote_currency_id', 'side'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rate', schema=None) as batch_op:
        batch_op.drop_constraint(constraint_name, type_='unique')

    # ### end Alembic commands ###
